### ISSUE TITLE
Fehlermeldung seit neuem Captcha

### ISSUE THREAD

**Issue by existful** [Niniib/anime4you-dl#5]
Ehlo,

Anime4You.one hat wohl ein neues Captcha, gibt es da ne möglichkeit dieses auch zu bypassen?

Hier RUST_BACKTRACE Log:

Danke.
```
[23:14] [exit@exodus]-[~]: RUST_BACKTRACE=1 ./anime4you-dl -e 1 -i 4708
[*] Found series ""
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2791:10
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: __libc_start_main
  17: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[23:14] [exit@exodus]-[~]: RUST_BACKTRACE=full ./anime4you-dl -e 1 -i 4708
[*] Found series ""
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2791:10
stack backtrace:
   0:     0x55cc45337464 - <unknown>
   1:     0x55cc4535703c - <unknown>
   2:     0x55cc45331017 - <unknown>
   3:     0x55cc45339685 - <unknown>
   4:     0x55cc45339371 - <unknown>
   5:     0x55cc45339cea - <unknown>
   6:     0x55cc453398d0 - <unknown>
   7:     0x55cc45356501 - <unknown>
   8:     0x55cc453564c5 - <unknown>
   9:     0x55cc4506ccb1 - <unknown>
  10:     0x55cc45069ad3 - <unknown>
  11:     0x55cc45088d93 - <unknown>
  12:     0x55cc453397b3 - <unknown>
  13:     0x55cc45341947 - <unknown>
  14:     0x55cc4533a250 - <unknown>
  15:     0x55cc4506d212 - <unknown>
  16:     0x7f14b10b1152 - __libc_start_main
  17:     0x55cc4505802e - <unknown>
  18:                0x0 - <unknown>
```

**Comment by Niniib** [comment]
Ich schau es mir mit @Fludixx an

**Comment by Atillon** [comment]
Hi,
also ich wollt nur mal fragen ob's schon irgendwelche Neuigkeiten zum Captcha-Problem gibt.

Danke schonmal im Vorhinein!

**Comment by motz0815** [comment]
Ich wär' auch daran interessiert, und hoffe, dass das Projekt hier noch weiter geht!
Das mit der Captcha ist schon schade...
Naja,
LG Motz

**Comment by Fludixx** [comment]
Hallo @motz0815 @Atillon @existful

Das Problem sollte jetzt behoben sein, ich hatte leider keine Zeit alles gründlich zu probieren, aber es sollte alles klappen. Bei Fehlern einfach eine Issue erstellen.

[Hier könnt ihr die neue version herrunterladen](https://github.com/Niniib/anime4you-dl/releases/tag/1.0.0)
